version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: final-api
    ports:
      - "8080:8080"
    networks:
      - app-network

  mvc:
    build:
      context: .
      dockerfile: Dockerfile
      target: final-web
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
